// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZXUqqIuGnEigWGBu6jVyHsHdt2etlwU',
    appId: '1:870427474311:android:b0854f80061031373b7b22',
    messagingSenderId: '870427474311',
    projectId: 'oracle-digital-test',
    storageBucket: 'oracle-digital-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFyx1TrvIsAidLUC-5-9_m_amcv7UZiXY',
    appId: '1:870427474311:ios:5f9e4c7e1b61d2c03b7b22',
    messagingSenderId: '870427474311',
    projectId: 'oracle-digital-test',
    storageBucket: 'oracle-digital-test.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFyx1TrvIsAidLUC-5-9_m_amcv7UZiXY',
    appId: '1:870427474311:ios:5f9e4c7e1b61d2c03b7b22',
    messagingSenderId: '870427474311',
    projectId: 'oracle-digital-test',
    storageBucket: 'oracle-digital-test.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
